//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindow_xaml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow_xaml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.MainWindow.xaml", typeof(MainWindow_xaml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Team.
        /// </summary>
        internal static string btnFavoriteInfo {
            get {
                return ResourceManager.GetString("btnFavoriteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        internal static string btnOppInfo {
            get {
                return ResourceManager.GetString("btnOppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        internal static string Championship_Men {
            get {
                return ResourceManager.GetString("Championship_Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        internal static string Championship_Women {
            get {
                return ResourceManager.GetString("Championship_Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string Language_Croatian {
            get {
                return ResourceManager.GetString("Language_Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose championship.
        /// </summary>
        internal static string lblChamp {
            get {
                return ResourceManager.GetString("lblChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose championship.
        /// </summary>
        internal static string lblChampionship {
            get {
                return ResourceManager.GetString("lblChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string lblExit {
            get {
                return ResourceManager.GetString("lblExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string lblLang {
            get {
                return ResourceManager.GetString("lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose resolution.
        /// </summary>
        internal static string lblRes {
            get {
                return ResourceManager.GetString("lblRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose resolution.
        /// </summary>
        internal static string lblResolution {
            get {
                return ResourceManager.GetString("lblResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save?.
        /// </summary>
        internal static string lblText {
            get {
                return ResourceManager.GetString("lblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of ties:.
        /// </summary>
        internal static string txtDraws {
            get {
                return ResourceManager.GetString("txtDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code:.
        /// </summary>
        internal static string txtFifaCode {
            get {
                return ResourceManager.GetString("txtFifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference:.
        /// </summary>
        internal static string txtGoalDifference {
            get {
                return ResourceManager.GetString("txtGoalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals conceded:.
        /// </summary>
        internal static string txtGoalsConceded {
            get {
                return ResourceManager.GetString("txtGoalsConceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals scored:.
        /// </summary>
        internal static string txtGoalsScored {
            get {
                return ResourceManager.GetString("txtGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of losses:.
        /// </summary>
        internal static string txtLosses {
            get {
                return ResourceManager.GetString("txtLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number played:.
        /// </summary>
        internal static string txtPlayed {
            get {
                return ResourceManager.GetString("txtPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of wins:.
        /// </summary>
        internal static string txtWins {
            get {
                return ResourceManager.GetString("txtWins", resourceCulture);
            }
        }
    }
}
