//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Number.
        /// </summary>
        internal static string AttendanceNumberCol {
            get {
                return ResourceManager.GetString("AttendanceNumberCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Team.
        /// </summary>
        internal static string AwayTeamCol {
            get {
                return ResourceManager.GetString("AwayTeamCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add picture.
        /// </summary>
        internal static string btnAddPicture {
            get {
                return ResourceManager.GetString("btnAddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to favorites.
        /// </summary>
        internal static string btnMoveToFav {
            get {
                return ResourceManager.GetString("btnMoveToFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print to PDF.
        /// </summary>
        internal static string btnPdfAttendance {
            get {
                return ResourceManager.GetString("btnPdfAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print to PDF.
        /// </summary>
        internal static string btnPdfCards {
            get {
                return ResourceManager.GetString("btnPdfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print to PDF.
        /// </summary>
        internal static string btnPdfGoals {
            get {
                return ResourceManager.GetString("btnPdfGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        internal static string btnRemoveFromFav {
            get {
                return ResourceManager.GetString("btnRemoveFromFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show attendance.
        /// </summary>
        internal static string btnShowAttendance {
            get {
                return ResourceManager.GetString("btnShowAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show players.
        /// </summary>
        internal static string btnShowPlayersCards {
            get {
                return ResourceManager.GetString("btnShowPlayersCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show players.
        /// </summary>
        internal static string btnShowPlayersGoals {
            get {
                return ResourceManager.GetString("btnShowPlayersGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        internal static string ChampionshipMen {
            get {
                return ResourceManager.GetString("ChampionshipMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        internal static string ChampionshipWomen {
            get {
                return ResourceManager.GetString("ChampionshipWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string CroatianOption {
            get {
                return ResourceManager.GetString("CroatianOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishOption {
            get {
                return ResourceManager.GetString("EnglishOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team.
        /// </summary>
        internal static string HomeTeamCol {
            get {
                return ResourceManager.GetString("HomeTeamCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageCol {
            get {
                return ResourceManager.GetString("ImageCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageColumn {
            get {
                return ResourceManager.GetString("ImageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        internal static string lblCaptain {
            get {
                return ResourceManager.GetString("lblCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the championship.
        /// </summary>
        internal static string lblChooserChampionship {
            get {
                return ResourceManager.GetString("lblChooserChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite players:.
        /// </summary>
        internal static string lblFavoritePl {
            get {
                return ResourceManager.GetString("lblFavoritePl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite player:.
        /// </summary>
        internal static string lblFavoritePlayer {
            get {
                return ResourceManager.GetString("lblFavoritePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite national team:.
        /// </summary>
        internal static string lblFavoriteTeam {
            get {
                return ResourceManager.GetString("lblFavoriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player:.
        /// </summary>
        internal static string lblMainPlayer {
            get {
                return ResourceManager.GetString("lblMainPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players:.
        /// </summary>
        internal static string lblPlayers {
            get {
                return ResourceManager.GetString("lblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        internal static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language.
        /// </summary>
        internal static string lblSelectLanguage {
            get {
                return ResourceManager.GetString("lblSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt number:.
        /// </summary>
        internal static string lblShirtNum {
            get {
                return ResourceManager.GetString("lblShirtNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string locationCol {
            get {
                return ResourceManager.GetString("locationCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Occurrences.
        /// </summary>
        internal static string NumberOfOccurrencesColumn {
            get {
                return ResourceManager.GetString("NumberOfOccurrencesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Occurrences.
        /// </summary>
        internal static string NumOfOccurrencesCol {
            get {
                return ResourceManager.GetString("NumOfOccurrencesCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string PlayerNameColumn {
            get {
                return ResourceManager.GetString("PlayerNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        internal static string PlNameCol {
            get {
                return ResourceManager.GetString("PlNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        internal static string Position_DF {
            get {
                return ResourceManager.GetString("Position_DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string Position_FW {
            get {
                return ResourceManager.GetString("Position_FW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goalkeeper.
        /// </summary>
        internal static string Position_GK {
            get {
                return ResourceManager.GetString("Position_GK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midfielder.
        /// </summary>
        internal static string Position_MF {
            get {
                return ResourceManager.GetString("Position_MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsToolStripMenuItem {
            get {
                return ResourceManager.GetString("settingsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string tcPlayers {
            get {
                return ResourceManager.GetString("tcPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string tpPlayers {
            get {
                return ResourceManager.GetString("tpPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking by yellow cards.
        /// </summary>
        internal static string tpRankingCards {
            get {
                return ResourceManager.GetString("tpRankingCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking by scored goals.
        /// </summary>
        internal static string tpRankingGoals {
            get {
                return ResourceManager.GetString("tpRankingGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking by number of visitors.
        /// </summary>
        internal static string tpRankingVisitors {
            get {
                return ResourceManager.GetString("tpRankingVisitors", resourceCulture);
            }
        }
    }
}
